# Generated by Django 3.2.6 on 2021-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='idName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
