# Generated by Django 3.2.6 on 2021-09-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='introEn',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='intro',
            new_name='introZh',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='lang',
            new_name='titleEn',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='motivation',
            new_name='titleZh',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
